### ISSUE TITLE
Update /user/history endpoint to also return user's name, prof pic

### ISSUE THREAD

**Issue by kevmodonahoe** [danignibus/outingBot#55]
Could you add the user's name and profile picture (for now the value can just be empty) to the response of the /user/history endpoint? I'm making a UserProfile page and need that info, and it seems that the appropriate endpoint to add those to are /user/history since I'm using the past outings in the UserProfile page as well.

Let me know if you have questions about this.

**Comment by danignibus** [comment]
Will do--also, currently this endpoint is only returning outing ID and reflection IDs for all completed outings by the user. This won't translate well for the actual list display. Thoughts on me also returning an image from one of the outing steps and the user's rating for that outing (for each outing in the list)?
